### PR TITLE
chore: fix markdown styles in storybook

### PR DESCRIPTION
**Pull request by denieler**
### Description

Fix markdown CSS styles in Storybook

### How to test

- Open storybook temploy
- Check markdown styles

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Screenshot 2022-06-23 at 20 29 27 |  Screenshot 2022-06-23 at 20 29 00  |

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

### CODE REVIEW

**Comment by augustobmoura** [comment]
The [demo](https://picasso.toptal.net/fx-fix-markdown-css/?2bdc19116f4c34d22a610ce7f4755171483d833f) is kinda broken
image

Maybe the github markdown is messing with other stuff

**Comment by denieler** [comment]
> Maybe the github markdown is messing with other stuff

@augustobmoura do you have some additional configs regarding dark theme or something like that? 🤔 to me it shows ok

**Comment by augustobmoura** [comment]
> > @augustobmoura do you have some additional configs regarding dark theme or something like that? thinking to me it is shown ok
> 
> My browser is on Dark mode, when I change it to Light mode it goes back to white. Maybe github-markdown has a special style for [`prefers-color-scheme: dark`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)?

Yep this is exactly what is going on:
image

**Comment by denieler** [comment]
@augustobmoura thank you 🙇 fixed that... but sorry, we are not going to support dark theme for now 😞

**Comment by augustobmoura** [comment]
> @augustobmoura thank you bow fixed that... but sorry, we are not going to support dark theme for now disappointed

Yeah, I'm not expecting it to support dark themes for now :sweat_smile:

**Comment by denieler** [comment]
> > @augustobmoura thank you bow fixed that... but sorry, we are not going to support dark theme for now disappointed
> 
> Yeah, I'm not expecting it to support dark themes for now 😅

I would love to ❤️ 😃 but it might take a while...

**Review by augustobmoura — APPROVED** [review]

**Comment by augustobmoura** [comment]
Demo looks good now

**Review by OndrejTuma — APPROVED** [review]
Markdown looks a lot better now 💪

**Pull request merged**
