### PR TITLE
fix: [SPT-1889] updated modal scrollable shades to fix resize inheritance

### PR DESCRIPTION
**Pull request by 13ANM**
[SPT-1889](https://toptal-core.atlassian.net/browse/SPT-1889)

### How to test

1. Go to [/?path=/story/overlays-modal--modal](https://picasso.toptal.net/SPT-1889-fix-modal-scrollable-shades-inheritance-on-resize/?path=/story/overlays-modal--modal) and open one of the modals
2. Resize the window height to make the content scrollable
3. Scroll so the shade effect will be in place
4. Resize back to non-scrollable content, the shade effect should dissapear
5. Compare to [current](https://picasso.toptal.net/?path=/story/overlays-modal--modal)

### Screenshots

https://user-images.githubusercontent.com/79158829/132189780-86ad126e-d00d-4311-94ed-a7e8a9c5c093.mov

https://user-images.githubusercontent.com/79158829/132189784-2d12f0f7-34c0-4df9-ab53-a6dcf384614e.mov

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

### CODE REVIEW

**Review by TomasSlama — CHANGES_REQUESTED** [review]
I have tested it in temploy and locally and I don't see any improvement in behavior. When I resize the window back to normal, shades don't disappear.

image

**Comment by the-teacher** [comment]
- I have it manually checked after adding `window.addEventListener('resize', updateShades)`
- Works better in contrast to the original version. Top shadow disappears.

Great if we have some throttling for reducing an amount of calls.

**Comment by 13ANM** [comment]
https://user-images.githubusercontent.com/79158829/132337429-5fb925fc-c494-4b62-b3b6-e90ee7861b4f.mov

https://user-images.githubusercontent.com/79158829/132337073-472564a0-219e-4fc6-bb82-ab97619b50f3.mov

This also fixes shades not appearing when resizing to scrollable content

**Comment by 13ANM** [comment]
@TomasSlama 47d921d

**Comment by 13ANM** [comment]
@toptal-anvil ping reviewers

**Review by the-teacher — APPROVED** [review]

**Review by TomasSlama — APPROVED** [review]
Works perfectly, great job! Thanks for contributing 👍

**Pull request merged**
