### PR TITLE
[FX-5297] Migrate Tag to TailwindCSS

### PR DESCRIPTION
**Pull request by sashuk**
[FX-5297]

### Description

This pull request adds missing changes in Tag styling based on the results of failing Client Portal visual tests. Please see the list of problems and solutions below.

References sources

- https://github.com/toptal/picasso/blob/master/packages/base/Tag/src/Tag/Tag.tsx
- https://github.com/toptal/picasso/blob/master/packages/base/Tag/src/TagRectangular/TagRectangular.tsx
- https://github.com/mui/material-ui/blob/v4.x/packages/material-ui/src/Chip/Chip.js

**How to review?**

Please do not review the very first commit that was already reviewed as part of the https://github.com/toptal/picasso/pull/4264.

**Discovered problems and solutions**

[Client Portal visual tests run](https://happo.io/a/431/p/1314/compare/857bac19826154f72bfd79c30ebd4380dddb2aa4/ef24e43237fe82412862e2e5ff369e5439763ae7) that was used to identify all errors. Issues that are not related to Tags are not mentioned below, mostly those are differences in button styling.

#### Billing/Details ✅ 

<details>
  <summary>More details</summary>

Client Portal usage

```jsx
    <Tag.Rectangular
      variant='dark-grey'
      data-testid='primary'
      className='PrimaryPaymentOptionTag'
    >
      PRIMARY
    </Tag.Rectangular>
```

```sass
.PrimaryPaymentOptionTag
  width: 102px
```

Storybook reproduction

```jsx
import React from 'react'
import {
  Tag,
  Container,
} from '@toptal/picasso'

const Example = () => (
  <Container flex>
    <Container>
      <Tag.Rectangular
        variant='dark-grey'
        data-testid='primary'
        style={{
          width: '102px'
        }}
      >
        PRIMARY
      </Tag.Rectangular>
    </Container>
  </Container>
)

export default Example
```
</details>

#### Client Lobby/FeaturedTalentsContent ✅ 

<details>
  <summary>More details</summary>

Difference between master and branch Client Portal – 2px

https://github.com/toptal/picasso/assets/1390758/325dcee1-9856-4022-94ee-52e482092961

Difference is in `marginRight` and `marginBottom` for Tag.Group – in both cases values are the same (`-0.5rem`), but the `fontSize` is different, so `-0.5rem` is calculated into `-6px` and in `-8px` in cases

Storybook reproduction

```jsx
import React from 'react'
import { Tag, Container } from '@toptal/picasso'

const Example = () => (
  <Container flex>
    <Container style={{width: '200px', border: '1px solid black', fontSize: '12px'}}>
      <Tag.Group>
        <Tag>Tag uno</Tag>
        <Tag>Tag duo</Tag>
        <Tag>Tag tres</Tag>
        <Tag>Tag quatro</Tag>
        <Tag>Tag cinque</Tag>
      </Tag.Group>
    </Container>
  </Container>
)

export default Example
```

</details>

#### Client Lobby/LastJobInquiry, Client Lobby/Lobby Header, JobStep, Multiple Jobs Step, ConsultationPage, EditJobContent, PlanPreviewModal, Onboarding, AgreementTypeStep, PriceTag, WizardFormContainer, JobDetails  – jumping label text ✅ 

<details>
  <summary>More details</summary>

The difference comes from line-height, the master branch has `19.2px` (which is a result of `12px x 1.6`) and new Tag implementation has it as `18px`. Tailwind font-size class also sets the line-height property, so we need to make Tag more configurable from outside by setting line-height to be inherited.

https://github.com/toptal/picasso/assets/1390758/5cb78f93-1bde-460e-85e2-aff0bdb7d401

</details>

#### InterviewInsightDrawer ✅ 

<details>
  <summary>More details</summary>

Icon needs to be properly copied, so Tailwind classes are applied to it as it used to work before

</details>

#### MenuWidget ✅ 

<details>
  <summary>More details</summary>

  Tag should not have `flex-wrap` applied

</details>

### How to test

- [Temploy](https://picasso.toptal.net/feature/migrate-tag)
- Compare Client Portal pull requests and their visual tests results
  - without changes from this pull request https://github.com/toptal/client-portal/pull/9067
  - with changes from this pull request https://github.com/toptal/client-portal/pull/9086

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [N/A] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [N/A] Annotate all `props` in component with documentation
- [N/A] Create `examples` for component
- [N/A] Ensure that deployed demo has expected results and good examples
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- [N/A] codemod is created and showcased in the changeset
- [x] test alpha package of Picasso in Client Portal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-5297]: https://toptal-core.atlassian.net/browse/FX-5297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-anvil ping reviewers

**Review by TomasSlama — APPROVED** [review]

**Review by mkrl — APPROVED** [review]
Fantastic job! I've approved the screenshot changes that look like a very minor trimming issue (looks like the overflow was not correct **before** the migration).

**Pull request merged**
