### PR TITLE
[FX-NULL] Revert debounce update

### PR DESCRIPTION
**Pull request by sashuk**
[FX-4727]

### Description

This pull request reverts `debounce@2.0` update (https://github.com/toptal/picasso/pull/4079), as it causes Staff Portal Cypress tests to fail with the following error

```
@staff-portal/clients-profile-app:   2) Enable Embedded Contract Signing
@staff-portal/clients-profile-app:        when the mutation is not successful
@staff-portal/clients-profile-app:          does not enable embedded contract signing and displays a form error:
@staff-portal/clients-profile-app:      Error: The following error originated from your application code, not from Cypress.
@staff-portal/clients-profile-app:   > Debounced method called with different contexts.
@staff-portal/clients-profile-app: When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
@staff-portal/clients-profile-app: This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
@staff-portal/clients-profile-app: https://on.cypress.io/uncaught-exception-from-application
@staff-portal/clients-profile-app:       at MutationObserver.debounced (http://localhost:8080/__cypress/src/main.js:726794:19)
@staff-portal/clients-profile-app: 
@staff-portal/clients-profile-app:   (Results)
@staff-portal/clients-profile-app:   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
@staff-portal/clients-profile-app:   │ Tests:        2                                                                                │
@staff-portal/clients-profile-app:   │ Passing:      0                                                                                │
@staff-portal/clients-profile-app:   │ Failing:      2                                                                                │
@staff-portal/clients-profile-app:   │ Pending:      0                                                                                │
@staff-portal/clients-profile-app:   │ Skipped:      0                                                                                │
@staff-portal/clients-profile-app:   │ Screenshots:  0                                                                                │
@staff-portal/clients-profile-app:   │ Video:        false                                                                            │
@staff-portal/clients-profile-app:   │ Duration:     31 seconds                                                                       │
@staff-portal/clients-profile-app:   │ Spec Ran:     profile-page/pages/ClientProfile/__tests__/profile-actions/enable-embedded-contr │
@staff-portal/clients-profile-app:   │               act-signing.cy.ts                                                                │
@staff-portal/clients-profile-app:   └────────────────────────────────────────────────────────────────────────────────────────────────┘
@staff-portal/clients-profile-app: ────────────────────────────────────────────────────────────────────────────────────────────────────
@staff-portal/clients-profile-app:             
```

The error is caused from latest major version of `debounce` and by https://github.com/sindresorhus/debounce/commit/95eef872be4d812c129fcc976caddc0a3446b5e6#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R28 in particular.

### How to test

- [Temploy](https://picasso.toptal.net/FX-NULL-revert-debounce-update)

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [N/A] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [N/A] Annotate all `props` in component with documentation
- [N/A] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-4727]: https://toptal-core.atlassian.net/browse/FX-4727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Review by augustobmoura — APPROVED** [review]

**Review by mkrl — APPROVED** [review]

**Review by dmaklygin — APPROVED** [review]

**Pull request merged**
