### PR TITLE
fix: [SPC-1154] removing additional padding on bottom of bordered sections

### PR DESCRIPTION
**Pull request by joantalarn**
[SPC-1154]

### Description

Bordered sections have consistent padding
Acceptance Criteria
Bottom padding is always the same as top in bordered sections

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Captura de pantalla de 2021-07-22 16-23-11 | Captura de pantalla de 2021-07-22 16-16-58|

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

[SPC-1154]: https://toptal-core.atlassian.net/browse/SPC-1154

### CODE REVIEW

**Comment by teimurjan** [comment]
@toptal-bot run deploy:documentation

**Review by denieler — APPROVED** [review]

**Review by teimurjan — APPROVED** [review]
Great job!

Nit: I'd add a comment describing the reason for zero padding for the last child.

**Comment by joantalarn** [comment]
@toptal-bot run all

**Review by elviocb — APPROVED** [review]
🚀

**Pull request merged**
