### PR TITLE
feat: support `CodeBlock`

### PR DESCRIPTION
**Pull request by TomasSlama**
[FX-4184]

### Description

The result of merging all separate PRs

### How to test

- [Temploy](https://picasso.toptal.net/feature/code-block)
- play with the storybook

### Screenshots

image

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)

**Breaking change**

- codemod is created and showcased in the changeset
- test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-4184]: https://toptal-core.atlassian.net/browse/FX-4184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by TomasSlama** [comment]
@toptal-anvil ping reviewers

**Comment by TomasSlama** [comment]
@toptal-anvil ping reviewers

**Comment by sashuk** [comment]
Do you think the output could be cleaned up a bit so it does not have those extra `<span/>`?

Screenshot 2023-08-10 at 10 28 03

**Review by sashuk — COMMENTED** [review]
Tested locally (temploy returns 500 error):
- copying and pasting from `RichText` line-by-line and as a whole
- toggling formatting for code blocks
- copying and pasting code blocks into each other, copying between editors, copying and pasting other types of rich text into code blocks and vice-versa

**Comment by mkrl** [comment]
Tested locally.

When only the empty lines are present in the editor, it lacks the margin that is there otherwise.


https://github.com/toptal/picasso/assets/18409292/eb953c45-bcb1-4ab6-870c-b4bd2bea0cc8



Also there's one thing that I'm not sure we should fix, but you can't really select existing part of the text and turn it into code block, it creates a block up until the existing node / paragraph boundary

https://github.com/toptal/picasso/assets/18409292/d5676ba9-6f00-4403-bc79-7d64a4bcecfd

**Comment by TomasSlama** [comment]
@mkrl The second issue is the same as we had with headings, it is still one paragraph as there is just `br` as space between.

I was actually trying even to convert just selected text, but it is pretty complex with a lot of edge cases. There is no specific requirement for this behaviour and I realized that there is not much benefit and it would be inconsistent with headings

**Comment by TomasSlama** [comment]
@toptal-anvil ping reviewers

**Comment by TomasSlama** [comment]
thank you guys for finding these bugs 🙇, I addressed them all

**Review by sashuk — APPROVED** [review]
Comments were addressed, thank you Tomas for such enormous work!

**Review by mkrl — APPROVED** [review]
Tremendous work, thank you!

**Pull request merged**
