### PR TITLE
fix: pixel gap problem

### PR DESCRIPTION
**Pull request by sashuk**
No Jira ticket.

### Description

Media queries in Picasso's breakpoints mechanism do not cover the 1px gap problem. The problem is that pixel values are not integers but float under certain conditions in web browsers.

Please see the problem by checking out [this](https://codepen.io/adamraider/full/MMKdeR) code pen.

The way it is treated by Twitter Bootstrap: https://github.com/twbs/bootstrap/blob/f0be063c9792f6fd123d933335efd0d8cc7f6f1f/site/content/docs/5.3/layout/breakpoints.md?plain=1#L122

The way it is treated by Flarum: https://github.com/flarum/framework/commit/761cc06697ae2921f69d896a3d54fabc715bb136#diff-e6448a88dd71c4d2959700443b3c8c642af1a8a759efb806df1f4e1a827784b2R125 (https://github.com/flarum/framework/issues/2915)

Example of engineers frustrated with this problem: https://github.com/elementor/elementor/issues/5221

### How to test

- Open https://6in9sf.csb.app/, zoom into the page, and try to bring the page to `1023.*px` size, **both** hook instances **will return false**

Screenshot 2023-05-26 at 19 17 01

- Open https://3t4kyd.csb.app/, zoom into the page, and try to bring the page to `1023.*px` size, one of the hook instances **will return true**

Screenshot 2023-05-26 at 19 35 15

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [N/A] Annotate all `props` in component with documentation
- [N/A] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [N/A] Covered with tests

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

### CODE REVIEW

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Comment by sashuk** [comment]
@toptal-bot run package:alpha-release

**Review by TomasSlama — APPROVED** [review]
One would expect that in modern browser we would not have to deal with such 💩. Good job fixing it 🙇

**Comment by sashuk** [comment]
@TomasSlama Thank you! Agree, it's so counter-intuitive🙂

**Comment by sashuk** [comment]
@toptal-anvil ping reviewers

**Review by mkrl — APPROVED** [review]
Awesome job! Tested the two cases with scaling, seems to do the job.

**Pull request merged**
