### PR TITLE
fix(codemod): fix removing children's attribute

### PR DESCRIPTION
**Pull request by ozgurkececioglu**
Fix and update for `remove-tooltip-variant` codemod

### Description

- Added missing codemod explanation to README
- Fixed codemod to not remove children component's ´variant´ prop
- Covered with test

### How to test

- codemod can be tested via alpha package

### Screenshots

before:
image

after:
Screen Shot 2022-05-16 at 17 11 41

### Development checks

- [x] Add changeset (we already did for v20.0.0)
- [x] Self reviewed
- [x] Covered with tests

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

### CODE REVIEW

**Comment by ozgurkececioglu** [comment]
@toptal-bot run package:alpha-release

**Comment by ozgurkececioglu** [comment]
@toptal-bot run package:alpha-release

**Comment by ozgurkececioglu** [comment]
Tested with Talent Portal and working as expected.

**Review by OndrejTuma — APPROVED** [review]
Code looks good 👍 
we should keep this in mind when creating codemods!

**Review by dmaklygin — APPROVED** [review]

**Review by denieler — APPROVED** [review]

**Pull request merged**
