### PR TITLE
feat(icon): add new icon

### PR DESCRIPTION
**Pull request by michal-bednarz**
[FX-2255]

### Description

Add missing "new" icon available in BASE

### How to test

- Run & test manually

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

[FX-2255]: https://toptal-core.atlassian.net/browse/FX-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by OleksandrNechai — APPROVED** [review]

**Review by denieler — APPROVED** [review]

**Review by OndrejTuma — APPROVED** [review]
Good 👍

**Review by TomasSlama — APPROVED** [review]

**Review by TomasSlama — CHANGES_REQUESTED** [review]
Changeset needs to be added. 👉 [Contribution](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md#release)

**Review by TomasSlama — APPROVED** [review]

**Comment by TomasSlama** [comment]
@toptal-bot run

**Comment by TomasSlama** [comment]
@toptal-bot run visual

**Comment by TomasSlama** [comment]
@toptal-bot run all

**Pull request merged**
