### PR TITLE
feat(Icon): add asterisk solid icon

### PR DESCRIPTION
**Pull request by sachalifs**
[PRO-2161](https://toptal-core.atlassian.net/browse/PRO-2161)

### Description

We need this asterisk solid icon for the VettedSkills initiative.

This icon is part of [our BASE design system](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/files/2fbda9fd-63f3-42e7-a9a8-135a6562ac01).

It will be used in the [new implementation](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/22aaaa3a11f480ef2d5aa808a63994a3b4178775/files/95e553a1-7136-42d8-8761-26f48e13ac46/layers/0344789B-B331-4E30-8B06-03989D1DF742?collectionId=e3b68eee-9a21-4740-b917-9494f80eb19c&collectionLayerId=c00f3d0a-271f-480e-a5d0-f52b38c0740b&mode=design&present=true) of our `Tag` component.

image

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

### CODE REVIEW

**Review by OleksandrNechai — APPROVED** [review]
Works as expected

**Review by alexanderpolyankin — APPROVED** [review]

**Review by denieler — APPROVED** [review]

**Review by Keksinautin — APPROVED** [review]

**Pull request merged**
