### PR TITLE
fix(Modal): fix width and height of top aligned modal on small screens

### PR DESCRIPTION
**Pull request by vvmarulin**
[FX-1833]

### Description

When the modal is top-aligned it is wider than the window on small screens. Also, the max height of the modal is set to 2rem vertical margin instead of 1rem margin that should be on small screens.

### How to test

- Go to  the ["Max Height" section](https://picasso.toptal.net/fx-1833-fix-top-aligned-modal/?path=/story/overlays-modal--modal#max-height) of the Modals page
- Edit the code as follows:

    ```diff
    - 14    <Modal onClose={onClose} open={open}>
    + 14    <Modal align='top' onClose={onClose} open={open}>
    ```
- Change emulated screen size to small mobile
- Click the "Open" button in the "Max Height" section. The modal should fit the screen with 1rem margins.
- Click the "Open Top Aligned Modal" button at the bottom of the Modals page. The modal should fit the screen with 1rem margins.

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| FireShot Capture 448 - Picasso - Modal - picasso toptal net | FireShot Capture 445 - Picasso - Modal - localhost |

### Review

- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [ ] Annotate all `props` in component with documentation
- [ ] Create `examples` for component
- [ ] Ensure that deployed demo has expected results and good examples
- [ ] Ensure that tests pass by running `yarn test`
- [ ] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

[FX-1833]: https://toptal-core.atlassian.net/browse/FX-1833

### CODE REVIEW

**Comment by denieler** [comment]
we have already a PR very similar to this one - https://github.com/toptal/picasso/pull/2072, can you please talk to @ertrzyiks and agree on the solution? 😃

**Comment by vvmarulin** [comment]
@denieler 
I know. But our PRs solve 2 different issues: [FX-1822](https://toptal-core.atlassian.net/browse/FX-1822) and [FX-1833](https://toptal-core.atlassian.net/browse/FX-1833). I discussed with @ertrzyiks if it worth having one PR for both issues. But we decided to go with two PRs to keep each PR relevant to the tickets.

**Review by denieler — APPROVED** [review]

**Comment by denieler** [comment]
@vmaxv got it 👍 cool!

**Review by vedrani — APPROVED** [review]

**Comment by vvmarulin** [comment]
@toptal-bot run all

**Comment by havenchyk** [comment]
@toptal-bot run tests

**Pull request merged**
