### PR TITLE
chore: remove .yarn files from repo

### PR DESCRIPTION
**Pull request by TomasSlama**
[FX-NNNN]

### Description

add needed yarn files to the `.gitattributes` file as it is listed in [docs](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored)

### Development checks

- [x] Self reviewed

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

### CODE REVIEW

**Review by denieler — APPROVED** [review]
It is bad to keep in the repo files we don't know why exist or we don't have explicit use from them. The reason is they confuse people. They take additional effort in maintenance.

**Comment by TomasSlama** [comment]
> It is bad to keep in the repo files we don't know why exist or we don't have explicit use from them. The reason is they confuse people. They take additional effort in maintenance.

@denieler so you think, we should remove `/.yarn/releases` from git? 🤔

**Review by separatio — APPROVED** [review]
@denieler In this case, I take these binaries as I take `yarn.lock` partially.

Ignoring that I know what `yarn.lock` does, I also know that it is best to keep it in .git.
So I'd go with the official docs recommendation from yarn, even though it's not super clear on their purpose. We could potentially see other failures later if we don't keep the binaries in git.

So I'm going to go for a :+1: on this PR.

**Comment by denieler** [comment]
> One more comment. As the documentation states:
> 
> image
> 
> Overall, keeping them won't hurt.

@separatio those docs are for `yarn v2` which we don't use at Toptal

**Comment by augustobmoura** [comment]
Even though this is on the docs, I never see it in the wild, and no major project uses it. If we want to keep the version of yarn consistent among the team we should just use an external versioning tool for the job

**Comment by augustobmoura** [comment]
Even though this is on the docs, I never see it in the wild, and no major project uses it. If we want to keep the version of yarn consistent among the team we should just use an external versioning tool for the job

**Comment by separatio** [comment]
Since the docs are for yarn v2, then we might as well ditch this change and the file, just adding it to .gitignore.

**Review by dmaklygin — APPROVED** [review]

**Comment by denieler** [comment]
I agree with @augustobmoura that we need consistency. And we know - we use yarn v1.

**Review by ozgurkececioglu — APPROVED** [review]

**Review by OndrejTuma — APPROVED** [review]

**Pull request merged**
