### PR TITLE
feat(SplitButton): add positive variant

### PR DESCRIPTION
**Pull request by denys-medynskyi**
[SCR-2739]

### How to test

- Visit [picasso](https://picasso.toptal.net/scr-2739-split-button-add-positive-variant/?path=/story/components-button--button)
- Scroll down to `Split Button`
- **Result**: find `positive` green variant

### Screenshots

Screen Shot 2022-04-29 at 2 02 34 PM

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

**Breaking change**

- [x] codemod is created and showcased in the changeset
- [x] test alpha package of Picasso in StaffPortal

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[SCR-2739]: https://toptal-core.atlassian.net/browse/SCR-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lstrzebinczyk — APPROVED** [review]

**Review by bigxiang — APPROVED** [review]

**Review by LashaJini — COMMENTED** [review]
Do we have a design for this? If so, could you provide link to it.

**Comment by denys-medynskyi** [comment]
@LashaJini This option was suggested as part of the hackathon project [provided here](https://docs.google.com/presentation/d/1SU56Kk02wJJf0nzfdIAVdFkoYFGMtsUJbt1NQh9kROI/edit#slide=id.gfbc1be4838_0_121).

**Review by LashaJini — APPROVED** [review]

**Review by TomasSlama — CHANGES_REQUESTED** [review]
On hover, it adds some weird pixels around.
image

Also, To me the look of it looks wrong, I think we are missing the separator between the buttons. Please share [the preview](https://picasso.toptal.net/scr-2739-split-button-add-positive-variant/?path=/story/components-button--button#variants) in `#-base-core` channel to approve the look of the button.

**Review by dmaklygin — APPROVED** [review]

**Comment by denys-medynskyi** [comment]
Abandon: rejected by **base team**

**Pull request closed without merging**
