### PR TITLE
feat(DatePicker): add footer background color

### PR DESCRIPTION
**Pull request by pedromonad**
[SDE-607](https://toptal-core.atlassian.net/browse/SDE-607)

### Description

Add footer background color on DatePicker

### How to test

- Access [https://picasso.toptal.net/sde-607-add-footer-background-color-property/](https://picasso.toptal.net/sde-607-add-footer-background-color-property)
- Verify footer background color example at Datepicker section
- Compare requirements in the ticket with implementation

### Screenshots

| Before.                                 | After.                                  |
| --------------------------------------- | --------------------------------------- |
| Screenshot_20221026_120057 | Screenshot_20221026_120106 |

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

**Breaking change**

- [n/a] codemod is created and showcased in the changeset
- [n/a] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

### CODE REVIEW

**Comment by pedromonad** [comment]
@toptal-anvil ping reviewers

**Review by yonathan-pineda — APPROVED** [review]

**Review by mateusbzerra — APPROVED** [review]
LGTM 💹

**Review by TomasSlama — COMMENTED** [review]
should we make the background color changeable? 🤔 For me, I would try to be consistent across all our projects, if we need to change the color, let's discuss with BASE and change it for everyone. I don't see the benefit in flexibility here. 🤷 

 BTW I cannot find the design in the BASE for this, do you have approval from them? 🤔

**Comment by OndrejTuma** [comment]
I agree with Tomas here. Picasso should follow BASE designs to offer consistency across projects. Even though this change does not modify our components by default, it allows to differ from other components. This should be approved by BASE team 👌

**Comment by pedromonad** [comment]
Hey @OndrejTuma and @TomasSlama, I agree with you guys, I didn't like to have done it using style but I did it because I need to have a feature flag to go back to the previous behavior. Because this initiative came from feedback where the user was not finding the link to start a conversation on Topchat about an End Engagement. I will discuss this with the BASE team.

**Review by TomasSlama — APPROVED** [review]
OK, thanks for explaining, then I think it makes sense to allow flexibility for experiments. Please if you realize that the darker grey color has better results, it would be great to push it to BASE -> Picasso

**Pull request merged**
