### PR TITLE
fix(PasswordInput): fix visibility of the password requirements

### PR DESCRIPTION
**Pull request by vvmarulin**
[FX-3097]
[TACO-1515]

### Description

When we remove the focus of the password input, the requirements get hidden after a small delay (500ms). If during this delay we focus the password input again we get in a wrong state, i.e. the password input is focused, but requirements are hidden.

### How to reproduce
1. Open https://picasso.toptal.net/?path=/story/picasso-forms-form--form#field-requirements
1. Click inside the password input field
1. Click on the label "Password". That will trigger a blur effect and a focus event right away

You will see that the input is focused but requirements are hidden. That's a bug.

https://user-images.githubusercontent.com/3861498/190341099-89555816-ec37-484a-b3b3-df2a1b979439.mp4

### How to test

- Open https://picasso.toptal.net/fix-password-input-requirements/?path=/story/picasso-forms-form--form#field-requirements
- Repeat the steps from the "Hot to reproduce" section
- Now everything should work as expected and field requirements should stay visible

### Development checks

- [x] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [x] Self reviewed
- [x] Covered with tests

**Breaking change**

- [x] codemod is created and showcased in the changeset
- [x] test alpha package of Picasso in StaffPortal

> All **_development checks_** should be done and set checked to pass the
> **GitHub Bot: TODOLess** action

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run package:alpha-release` - Release alpha version
- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-3097]: https://toptal-core.atlassian.net/browse/FX-3097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TACO-1515]: https://toptal-core.atlassian.net/browse/TACO-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ozgurkececioglu — APPROVED** [review]
Tested on my local and working great 👏 
Thanks for the fix and explanation 🙇‍♂️ ❤️

**Review by OndrejTuma — APPROVED** [review]
Code looks good 👍 
Tested in temploy, thanks for the fix 💪

**Review by LashaJini — COMMENTED** [review]
Same issue, but instead when we hold mouse long enough.

https://user-images.githubusercontent.com/72510037/190585494-d4c8f6a4-bc3b-4a2c-8548-4d87f8bcae6b.mp4

**Comment by ozgurkececioglu** [comment]
> @vvmarulin Same issue, but instead when we **hold** mouse long enough.
> 
>  simplescreenrecorder-2022-09-16_11.48.10.mp4

@LashaJini I think this is about losing focus while waiting mouse is pressed. I think that's ok since after clicking to input once again, it is working as expected. It wasn't previously. Wdyt @vvmarulin?

**Review by separatio — APPROVED** [review]
Code looks ok. Tested and works as expected. Thank you for your contribution. :bow:

**Comment by separatio** [comment]
FYI @LashaJini I also agree with @ozgurkececioglu . The details should be displayed only while the input is focused.

**Pull request merged**
