### PR TITLE
chore: remove trim vulnerability

### PR DESCRIPTION
**Pull request by TomasSlama**
[FX-2533]

### Description

This PR removes `trim` [vulnerability](https://github.com/toptal/picasso/security/dependabot/19).

`trim` is used by `remark-parse`, which is dependency of multiple packages. We need `remark-parse` to have version 9+.
1. **react-markdown**
  - upgraded to the latest possible version for us `6.0.3`. Version `7+` is in ESM only. This update was enough to upgrade the dependency of `remark-parse` from 5 to 9 ✅ 
  - we use `react-markdown` only for components in the storybook and we use it in a very simple way. None of the breaking changes from version 4 to 6 did touch our code.

2. **prettierx**
  - has the dependency of `remark-parse@5`, since we don't use `prettierx` anymore, but we use `prettier` directly, I have removed this dependency ✅ 

3. **@storybook/react**
  - we already have the latest version, which uses `remark-parse@8` ❎ 
  - so upgrade of dependencies does not help in this case, I had to add `trim` to the resolutions.

### How to test

- CI is green
- storybook looks and works the same as in the master

### Review

- [x] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [x] Annotate all `props` in component with documentation
- [x] Create `examples` for component
- [x] Ensure that deployed demo has expected results and good examples
- [x] Ensure that tests pass by running `yarn test`
- [x] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [x] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
5. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
6. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-2533]: https://toptal-core.atlassian.net/browse/FX-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by TomasSlama** [comment]
@toptal-bot run all

**Review by ozgurkececioglu — APPROVED** [review]
Tested some pages, LGTM 👍

**Review by OndrejTuma — APPROVED** [review]
Since you added trim to resolutions, you probably didnt need to update react-markdown. But since it does not break anything, its a good move 👍

**Comment by TomasSlama** [comment]
> Since you added trim to resolutions, you probably didnt need to update react-markdown. But since it does not break anything, its a good move 👍

@OndrejTuma I think it is good practice to remove the vulnerability issue from as many packages as you can. In the future when `@storybook/react` will fix the issue, we will have to update only one package and we can remove the resolutions.

**Pull request merged**
