### PR TITLE
chore: [FX-2401] Simplify usage of codemods

### PR DESCRIPTION
**Pull request by denieler**
[FX-2401]

### Description

Make usage of codemods simpler:
- codemods don't need to be installed in the projects anymore
- don't need a special command for monorepo/spa apps

Now codemods can be run via
```
npx @toptal/picasso-codemod v17.0.0/typography-sizes
```
without a need to install the package directly.

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-bot run all` - Run whole pipeline
- `@toptal-bot run build` - Check build
- `@toptal-bot run visual` - Run visual tests
- `@toptal-bot run deploy:documentation` - Deploy documentation
- `@toptal-bot run package:alpha-release` - Release alpha version

</details>

<details>
<summary>PR Review Guidelines</summary>
<br />

#### When to approve? ✅

**You are OK** with merging this PR and

1. You have no extra requests.
2. You have optional requests.
   1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from makeCircle to getCircle`)

#### When to request changes? ❌

**You are not OK** with merging this PR because

1. Something is broken after the changes.
2. Acceptance criteria is not reached.
3. Code is dirty.

#### When to comment (neither ✅ nor ❌)

**You want your comments to be addressed** before merging this PR in cases like:

1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.

#### How to handle the comments?

1. An owner of a comment is the only one who can resolve it.
2. An owner of a comment must resolve it when it's addressed.
3. A PR owner must reply with ✅ when a comment is addressed.

</details>

[FX-2401]: https://toptal-core.atlassian.net/browse/FX-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by denieler** [comment]
@toptal-bot run package:alpha-release

**Review by dmaklygin1 — APPROVED** [review]

**Comment by denieler** [comment]
@toptal-bot run package:alpha-release

**Comment by denieler** [comment]
@toptal-bot run package:alpha-release

**Comment by denieler** [comment]
@toptal-bot run package:alpha-release

**Pull request merged**
